### ISSUE TITLE
Startup fails with latest commit

### ISSUE THREAD

**Issue by dumpfheimer** [zigpy/zigpy-znp#79]
Hi!

This is more of a FIY, not a complaint or anything. I am aware of the possibility of this happening when using the dev code.
Anyway:

Since your last commit ZHA stopped starting in Home Assistant. Here is the exception:

2021-07-22 15:31:19 INFO (MainThread) [zigpy_znp.zigbee.application] Permitting joins for 0 seconds
2021-07-22 15:31:19 DEBUG (MainThread) [zigpy_znp.uart] Closing serial port
2021-07-22 15:31:19 ERROR (MainThread) [zigpy.application] Couldn't start application
2021-07-22 15:31:19 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry ZZH! for zha
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/zha/__init__.py", line 102, in async_setup_entry
    await zha_gateway.async_initialize()
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/zha/core/gateway.py", line 152, in async_initialize
    self.application_controller = await app_controller_cls.new(
  File "/srv/homeassistant/lib/python3.9/site-packages/zigpy/application.py", line 74, in new
    await app.startup(auto_form)
  File "/srv/homeassistant/lib/python3.9/site-packages/zigpy_znp/zigbee/application.py", line 193, in startup
    return await self._startup(
  File "/srv/homeassistant/lib/python3.9/site-packages/zigpy_znp/zigbee/application.py", line 305, in _startup
    await self.permit(time_s=0)
  File "/srv/homeassistant/lib/python3.9/site-packages/zigpy_znp/zigbee/application.py", line 711, in permit
    if self._version_rsp.CodeRevision < 20210708:
AttributeError: 'NoneType' object has no attribute 'CodeRevision'

Looks like when the CC2531 "prevent joining at startup" workaround will call the "permit" function where self._version_rsp is still None because it would be set in line 352

**Comment by puddly** [comment]
Oops, thanks for letting me know!
